<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>GoldenDelicious.DiscordBot.Data</AssemblyName>
        <RootNamespace>GoldenDelicious.DiscordBot.Data</RootNamespace>
        <IsAspireProjectResource>false</IsAspireProjectResource>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" />
    </ItemGroup>

</Project>
