<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
      <IsPackable>false</IsPackable>
    <UserSecretsId>72de8219-f42a-4b9d-958f-8e20460eba8d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
      <PackageReference Include="Aspire.Hosting.AppHost" />
      <PackageReference Include="Aspire.Hosting.RabbitMQ" />
      <PackageReference Include="Aspire.Hosting.Redis" />
      <PackageReference Include="Aspire.Hosting.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DiscordBot.API\DiscordBot.API.csproj" />
    <ProjectReference Include="..\DiscordBot.DatabaseMigration\DiscordBot.DatabaseMigration.csproj" />
    <ProjectReference Include="..\DiscordBot.Service\DiscordBot.Service.csproj" />
    <ProjectReference Include="..\GoldenDelicious.Common\GoldenDelicious.Common.csproj" IsAspireProjectResource="false" />
  </ItemGroup>

</Project>
